### ISSUE TITLE
error building go code

### ISSUE THREAD

**Issue by srt180** [ntop/libebpfflow#10]
Error occurs when I run `make go_ebpflowexport`:

> ebpf/bpf.go:222:44: filled_event.cgroup_id undefined (type *_Ctype_struct___0 has no field or method cgroup_id)
ebpf/bpf.go:225:74: filled_event.event undefined (type *_Ctype_struct___0 has no field or method event)
ebpf/bpf.go:231:74: filled_event.event undefined (type *_Ctype_struct___0 has no field or method event)
ebpf/bpf.go:238:27: filled_event.docker.dname undefined (type _Ctype_struct___2 has no field or method dname)
ebpf/bpf.go:240:50: filled_event.docker.dname undefined (type _Ctype_struct___2 has no field or method dname)

Obvious the golang code ebpf_flow.go using the structure `eBPFevent` but incomplete in c code.

> typedef struct {
  ktime_t ktime;
  char ifname[IFNAMSIZ];
  struct timeval event_time;
  u_int8_t ip_version, sent_packet;
  u16 etype;
  union {
    struct ipv4_addr_t v4;
    struct ipv6_addr_t v6;
  } addr;
  u8  proto;
  u16 sport, dport;
  u32 latency_usec;
  u16 retransmissions;
  struct taskInfo proc, father;
  char container_id[CONTAINER_ID_LEN];
  struct {
    char *name;
  } docker;  
  struct {
    char *name;
    char *pod;
    char *ns;
  } kube;
} eBPFevent;

**Comment by samuelesabella** [comment]
Thank you for the feedback, the inconsistencies have been fixed in a927b9eb8e97700e1b530112455e6f36af3fca84
