### ISSUE TITLE
problem using libebpflow on ubuntu 19.10 (eoan ermine) 

### ISSUE THREAD

**Issue by faustothegrey** [ntop/libebpfflow#13]
Hi,
I'm trying to use libebpfflow on ubuntu 19.10 ( eoan ermine ). I'm able to compile but
when I try to execute ebpflowexport (sudo ./ebpflowexport -tio) I get the same general error
"ebpf_initialization_failed" due to several compilation errors (12 errors total).
Any clues why this could happen ? Thanks in advance. Fausto.

Welcome to ebpflowexport v.1.0.191118
(C) 2018-19 ntop.org
Initializing eBPF [Legacy API]...
In file included from /virtual/main.c:22:
In file included from include/net/sock.h:46:
In file included from include/linux/netdevice.h:42:
In file included from include/net/netprio_cgroup.h:11:
In file included from include/linux/cgroup.h:28:
In file included from include/linux/cgroup-defs.h:22:
In file included from include/linux/bpf-cgroup.h:5:
include/linux/bpf.h:115:3: error: variable has incomplete type 'struct bpf_spin_lock'
(struct bpf_spin_lock){};
^~~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:114:11: note: forward declaration of 'struct bpf_spin_lock'
*(struct bpf_spin_lock *)(dst + map->spin_lock_off) =
^
include/linux/bpf.h:125:22: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
memcpy(dst + off + sizeof(struct bpf_spin_lock),
^ ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
memcpy(dst + off + sizeof(struct bpf_spin_lock),
^
include/linux/bpf.h:126:22: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
src + off + sizeof(struct bpf_spin_lock),
^ ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
memcpy(dst + off + sizeof(struct bpf_spin_lock),
^
include/linux/bpf.h:127:34: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_spin_lock'
map->value_size - off - sizeof(struct bpf_spin_lock));
^ ~~~~~~~~~~~~~~~~~~~~~~
include/linux/bpf.h:125:36: note: forward declaration of 'struct bpf_spin_lock'
memcpy(dst + off + sizeof(struct bpf_spin_lock),
^
include/linux/bpf.h:454:39: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
u32 access_flags = map->map_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
^
include/linux/bpf.h:454:59: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
u32 access_flags = map->map_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
^
include/linux/bpf.h:459:21: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
if (access_flags & BPF_F_RDONLY_PROG)
^
include/linux/bpf.h:461:26: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
else if (access_flags & BPF_F_WRONLY_PROG)
^
include/linux/bpf.h:469:26: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
return (access_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG)) !=
^
include/linux/bpf.h:469:46: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
return (access_flags & (BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG)) !=
^
include/linux/bpf.h:470:10: error: use of undeclared identifier 'BPF_F_RDONLY_PROG'
(BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);
^
include/linux/bpf.h:470:30: error: use of undeclared identifier 'BPF_F_WRONLY_PROG'
(BPF_F_RDONLY_PROG | BPF_F_WRONLY_PROG);

omissis
49 warnings and 12 errors generated.
Unable to initialize libebpfflow: ebpf_initialization_failed
eBPF terminated

**Comment by samuelesabella** [comment]
Hello. This issue is caused by a [known bug](https://bugs.launchpad.net/ubuntu/+source/bpfcc/+bug/1848137). I was able to compile and execute the code by building BCC tools from source as suggested in [iovisor/bcc](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary).
