### ISSUE TITLE
no data availabe in ntopng interface

### ISSUE THREAD

**Issue by ahlamm01** [ntop/libebpfflow#4]
the ntopng don't receive the data from the nprobe, no data available on ntopng interface web 

this is my config:

ntopng:

-G=/var/run/ntopng.pid
--interface="tcp://127.0.0.1:5556
--https-port "3001"
--http-port "0"

nprob:

--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none

nprobe and ntponng are installed on the same server (ubuntu 16.04)

the nrpobe receive the data from my firewall 

I have this  error with ntopng

#ntopng -i tcp://127.0.0.1:5556

 WARNING: Unable to open store /var/lib/ntopng/12/alerts/alerts_v7.db
 [AlertsManager.cpp:942] ERROR: Unable to prepare statement for query SELECT count(*) FROM closed_alerts  .
[AlertsManager.cpp:986] ERROR: Unable to prepare statement for query SELECT count(*) FROM flows_alerts  .
 [AlertsManager.cpp:942] ERROR: Unable to prepare statement for query SELECT count(*) FROM engaged_alerts WHERE alert_severity=2.
[Ntop.cpp:1996] Registered interface tcp://127.0.0.1:5556 [If Idx: 3] [id: 13]
 [Ntop.cpp:1996] Registered interface tcp://127.0.0.1:5556 [If Idx: 4] [id: 14]

any idea please 

thank you in advance

**Comment by emanuele-f** [comment]
Hi, this does not seem related to libebpfflow but to ntopng, so please open an issue here: https://github.com/ntop/ntopng . Please report ntopng and nprobe versions used (output of `--version`).

**Comment by ahlamm01** [comment]
OK 

thank you

**Comment by ahlamm01** [comment]
Hello,

The ticket is created,

no data available in ntopng web interface #2421

Could you please help me to resolve it

Regards
